FROM python:3.8-alpine

RUN apk update && \
    apk add --no-cache tzdata

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Just copy only what is needed
COPY COC_MESSAGE.txt .
COPY WELCOME_MESSAGE.txt .
COPY README.md .
COPY bot.py .

CMD [ "python", "./bot.py" ]
